apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce   # This means the volume can only be mounted by a single node
  resources:
    requests:
      storage: 10Gi    # The amount of storage you want to request (10 GB in this case)
  storageClassName: standard  # The storage class to use (depends on your setup)

