apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432        # Port on which the service is exposed
      targetPort: 5432   # Port the app is listening on
  selector:
    app: postgresql     # This ensures the service routes traffic to the correct pod
  type: ClusterIP       # This is the default type for internal communication (use LoadBalancer for external access)

